apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: movie-service
    type: be-service
  name: movie-service-pod
  namespace: movies-ns
spec:
  containers:
    - envFrom:
        - configMapRef:
            name: movie-service-config-map
        - secretRef:
            name: movie-service-secret
      image: sachingorade/movie-service:0.3
      name: movie-service
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      resources: { }
  dnsPolicy: ClusterFirst
  restartPolicy: Always