apiVersion: v1
kind: Service
metadata:
  labels:
    app: movie-service
    type: e-service
  name: movie-service
  namespace: movies-ns
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32080
  selector:
    app: movie-service
  type: NodePort